// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package roadmapgen

import (
	"time"

	"github.com/google/uuid"
)

type Roadmap struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"user_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	IsPublic    bool      `json:"is_public"`
	Category    string    `json:"category"`
	Tags        []string  `json:"tags"`
	Difficulty  string    `json:"difficulty"`
	CreatedAt   time.Time `json:"created_at"`
}
