// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package roadmapgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Roadmap struct {
	ID          uuid.UUID   `json:"id"`
	OwnerID     pgtype.UUID `json:"owner_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	IsPublic    pgtype.Bool `json:"is_public"`
	Category    pgtype.Text `json:"category"`
	Tags        []string    `json:"tags"`
	Difficult   pgtype.Text `json:"difficult"`
	CreatedAt   time.Time   `json:"created_at"`
}
