// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package checkpointgen

import (
	"time"

	"github.com/google/uuid"
)

type Checkpoint struct {
	ID            uuid.UUID `json:"id"`
	RoadmapID     uuid.UUID `json:"roadmap_id"`
	Title         string    `json:"title"`
	Description   string    `json:"description"`
	Position      int32     `json:"position"`
	Type          string    `json:"type"`
	Status        string    `json:"status"`
	EstimatedTime int32     `json:"estimated_time"`
	RewardPoints  int32     `json:"reward_points"`
	CreatedAt     time.Time `json:"created_at"`
}

type UserCheckpoint struct {
	UserID       uuid.UUID `json:"user_id"`
	CheckpointID uuid.UUID `json:"checkpoint_id"`
	Status       string    `json:"status"`
}
