// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package checkpointgen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Checkpoint struct {
	ID            uuid.UUID   `json:"id"`
	RoadmapID     uuid.UUID   `json:"roadmap_id"`
	Title         string      `json:"title"`
	Description   string      `json:"description"`
	Position      int32       `json:"position"`
	Type          string      `json:"type"`
	Status        string      `json:"status"`
	EstimatedTime int32       `json:"estimated_time"`
	RewardPoints  pgtype.Int4 `json:"reward_points"`
	CreatedAt     time.Time   `json:"created_at"`
}
