name: backend

on:
  push:
    paths:
      - '**.go'
      - '**.proto'
      - '**.sql'
      - 'go.*'
      - '.github/workflows/backend.yml'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Install CLI tools
        run: |
          go install github.com/sqlc-dev/sqlc/cmd/sqlc@latest

      - name: Add Go bin to PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: sqlc generate
        run: sqlc generate
  
  build: 
    needs: lint 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Go build
        run: |
          go mod tidy
          go build ./..

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
            go-version: '1.24'
        
      - name: Run tests
        run: go test ./...