// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package usergen

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Type      pgtype.Text `json:"type"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

type UserCheckpoint struct {
	ID           uuid.UUID        `json:"id"`
	UserID       pgtype.UUID      `json:"user_id"`
	CheckpointID pgtype.UUID      `json:"checkpoint_id"`
	CompletedAt  pgtype.Timestamp `json:"completed_at"`
}

type UserRoadmap struct {
	ID        uuid.UUID        `json:"id"`
	UserID    pgtype.UUID      `json:"user_id"`
	RoadmapID pgtype.UUID      `json:"roadmap_id"`
	StartedAt pgtype.Timestamp `json:"started_at"`
}
